<?xml version="1.0" ?>

<robot name="panda" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find moveit_resources_panda_description)/urdf/panda.urdf.xacro" />

    <xacro:property name="mob_base_height" value="0.18"/>

    <!-- Fixed joint from your parent link to panda_link0 -->
    <joint name="panda_on_base_link" type="fixed">
      <parent link="base_link"/>
      <child  link="panda_link0"/>
      <origin xyz="0.0 0 ${mob_base_height/2}" rpy="0 0 0"/>
    </joint>

    <gazebo>
      <plugin filename="gz_ros2_control-system" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
        <parameters>/home/reuben/moveit_ws/src/panda_moveit_config/config/ros2_controllers.yaml</parameters>
      </plugin>
    </gazebo>


    <ros2_control name="panda_gz_system" type="system">
      <hardware>
        <plugin>gz_ros2_control/GazeboSimSystem</plugin>
      </hardware>

      <!-- Arm joints -->
      <joint name="panda_joint1">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint2">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint3">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint4">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint5">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint6">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <joint name="panda_joint7">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>

      <!-- Optional: gripper joints  -->
      
      <joint name="panda_finger_joint1">
        <command_interface name="position"/>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="panda_finger_joint2">
        <!-- <command_interface name="position"/> -->       <!-- Caused major issues-->
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </joint>
    
    </ros2_control>



</robot>