<?xml version="1.0"?>
<robot name="sonny_main" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find sonny_description)/urdf/panda_mount.urdf.xacro"/>

  <!-- *************** MACROS AND PROPERTIES ****************  -->

  <!-- Define robot constants -->
  <!-- <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.42"/> -->
  <xacro:property name="base_width" value="0.51"/>
  <xacro:property name="base_length" value="0.62"/>
  <xacro:property name="base_height" value="0.18"/>
  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.12"/>
  <xacro:property name="caster_xoff" value="0.14"/>

  <xacro:property name="box_dim" value="0.15"/>

  <!-- Define inertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>

    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
    
  </xacro:macro>

  <!-- *************** LINKS AND JOINTS **************** -->

  <!-- Robot Base -->
  <link name="base_link">

    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Grey">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>    

  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint">
     <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

  <!-- Caster Wheel -->
  <link name="front_caster">

    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>

  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>

  <link name='imu_link'>

    <visual name="imu_link_visual">
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <collision name="imu_link_collision">
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>

  </link>

  <joint name='imu_joint' type='fixed'>
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0.0 0.01" rpy="0 0 0"/>
  </joint>

  <link name='lidar_link'>

    <visual name="lidar_link_visual">
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </visual>

    <collision name="lidar_link_collision">
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="0.125" r="0.0508" h="0.055"/>

  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${caster_xoff} 0.0 0.12" rpy="0 0 0"/>
  </joint>

  <gazebo reference="drivewhl_l_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="drivewhl_r_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
  </gazebo>

  <gazebo reference="front_caster">
      <mu1 value="0.1"/>
      <mu2 value="0.1"/>
  </gazebo>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <!-- <odom_publisher_frequency>50</odom_publisher_frequency> -->
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.4</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      
      <!-- limits -->
      <!-- <max_wheel_torque>20</max_wheel_torque> -->
      <max_linear_acceleration>0.5</max_linear_acceleration>

      <!-- input -->
      <topic>/demo/cmd_vel</topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <!-- output -->
      <odom_topic>/demo/odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
      <tf_topic>/tf</tf_topic>
    </plugin>

    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <!-- <update_rate>50</update_rate>
      <joint_name>left_wheel_joint</joint_name>
      <joint_name>right_wheel_joint</joint_name> -->
    </plugin>

  </gazebo>  

  <!-- Lidar Plugin -->
  <gazebo reference="lidar_link">
      <sensor name="lidar" type="gpu_lidar">
        <!-- <pose>0 0 0 0 0 0</pose> -->
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <lidar>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1.000000</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.5</min>
            <max>5.0</max>
            <!-- <max>4.5</max> -->
            <!-- <resolution>0.015000</resolution> -->
            <resolution>0.010000</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </lidar>
        <topic>scan</topic>
        <gz_frame_id>lidar_link</gz_frame_id>
      </sensor>
  </gazebo>


  <!-- IMU Plugin -->
  <gazebo reference="imu_link">
      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>demo/imu</topic>
        <gz_frame_id>imu_link</gz_frame_id>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
      </sensor>
  </gazebo>


  <!-- *************** FRANKA PANDA **************** -->

  <xacro:add_panda_arm parent_link="base_link" base_xyz="0.0 0 ${base_height/2}" base_rpy="0 0 0"/>


  <!-- *************** BOXES **************** -->

  <!-- Green Box -->
  <link name="green_box">

    <visual>
      <geometry>
        <mesh filename="file:///home/reuben/moveit_ws/install/sonny_description/share/sonny_description/meshes/Green_Box.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="Green">
        <color rgba="0.0 1 0.0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <mesh filename="file:///home/reuben/moveit_ws/install/sonny_description/share/sonny_description/meshes/Green_Box.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>    

    <xacro:box_inertia m="5" w="0.15" d="0.15" h="0.15"/>

  </link>

  <joint name="green_box_joint" type="fixed">
    <parent link="base_link"/>
    <child link="green_box"/>
    <origin rpy="0 0 0" xyz="${(-wheel_xoff)-(box_dim/2)} ${base_width/3} ${(base_height/2)+(box_dim/2)}"/>
  </joint>


  <!-- Red Box -->
  <link name="red_box">

    <visual>
      <geometry>
        <mesh filename="file:///home/reuben/moveit_ws/install/sonny_description/share/sonny_description/meshes/Red_Box.stl" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="Red">
        <color rgba="1.0 0.0 0.0 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <mesh filename="file:///home/reuben/moveit_ws/install/sonny_description/share/sonny_description/meshes/Red_Box.stl" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>    

    <xacro:box_inertia m="5" w="0.15" d="0.15" h="0.15"/>

  </link>

  <joint name="red_box_joint" type="fixed">
    <parent link="base_link"/>
    <child link="red_box"/>
    <origin rpy="0 0 0" xyz="${(-wheel_xoff)-(box_dim/2)} ${-base_width/3} ${(base_height/2)+(box_dim/2)}"/>
  </joint>


</robot>