<?xml version="1.0"?>
<robot name="sonny_base" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Include Panda arm macro -->
  <xacro:include filename="$(find sonny_description)/urdf/panda_mount.urdf.xacro"/>

  <!-- =========================
       Constants
  ========================== -->
  <xacro:property name="base_width"  value="0.31"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width"  value="0.04"/>
  <xacro:property name="wheel_ygap"   value="0.025"/>
  <xacro:property name="wheel_zoff"   value="0.05"/>
  <xacro:property name="wheel_xoff"   value="0.12"/>

  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- =========================
       Inertia helper macros
  ========================== -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(m/12) * (h*h + d*d)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(m/12) * (w*w + d*d)}"
        iyz="0.0"
        izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(m/12) * (3*r*r + h*h)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(m/12) * (3*r*r + h*h)}"
        iyz="0.0"
        izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <inertia
        ixx="${(2/5) * m * (r*r)}"
        ixy="0.0"
        ixz="0.0"
        iyy="${(2/5) * m * (r*r)}"
        iyz="0.0"
        izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- =========================
       Base links
  ========================== -->

  <!-- Canonical link (no inertial in original SDF) -->
  <link name="base_link">
    <visual name="base_link_visual">
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="base_cyan">
        <color rgba="0 1 1 1"/>
      </material>
    </visual>

    <collision name="base_link_collision">
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>


  <!-- Mount Panda on top of the base_link -->
  <xacro:add_panda_arm
      parent_link="base_link"
      base_xyz="0.5 0 ${base_height/2}"
      base_rpy="0 0 0"/>



  <!-- Footprint (has inertial in original SDF) -->
  <link name="base_footprint">
    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="base_footprint"/>
    <!-- from pose relative_to="base_link">
         0 0 - (wheel_radius + wheel_zoff) 0 0 0
    -->
    <origin xyz="0 0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- =========================
       Wheels (macro)
  ========================== -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual name="${prefix}_link_visual">
        <!-- original pose: rpy = pi/2,0,0 -->
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="${prefix}_gray">
          <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
      </visual>

      <collision name="${prefix}_link_collision">
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
    </link>

    <!-- In SDF this is revolute with +/-inf; URDF uses continuous -->
    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${prefix}_link"/>
      <!-- pose relative_to="base_link":
           x_reflect*wheel_xoff,
           y_reflect*(base_width/2 + wheel_ygap),
           -wheel_zoff
      -->
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Drive wheels (same macros as SDF) -->
  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1"/>

  <!-- =========================
       Front caster
  ========================== -->
  <link name="front_caster">
    <visual name="front_caster_visual">
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="caster_white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>

    <collision name="front_caster_collision">
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia
      m="0.5"
      r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="front_caster"/>
    <!-- pose relative_to="base_link":
         caster_xoff, 0, -(base_height/2)
    -->
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
  </joint>

  <!-- =========================
       IMU link
  ========================== -->
  <link name="imu_link">
    <visual name="imu_link_visual">
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>

    <collision name="imu_link_collision">
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="imu_link"/>
    <!-- pose relative_to="base_link">0 0 0.01 0 0 0 -->
    <origin xyz="0 0 0.01" rpy="0 0 0"/>
  </joint>

  <!-- =========================
       LIDAR link
  ========================== -->
  <link name="lidar_link">
    <visual name="lidar_link_visual">
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </visual>

    <collision name="lidar_link_collision">
      <geometry>
        <cylinder radius="0.0508" length="0.055"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="0.125" r="0.0508" h="0.055"/>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <!-- pose relative_to="base_link">0 0 0.12 0 0 0 -->
    <origin xyz="0 0 0.12" rpy="0 0 0"/>
  </joint>

  <!-- =========================
       Gazebo extensions
       (sensors + system plugins)
  ========================== -->

  <!-- IMU sensor on imu_link -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>demo/imu</topic>
      <gz_frame_id>imu_link</gz_frame_id>
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- LIDAR sensor on lidar_link -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <topic>scan</topic>
      <gz_frame_id>lidar_link</gz_frame_id>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>3.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

  <!-- Model-level Gazebo system plugins -->
  <gazebo>
    <!-- Diff drive (gz-sim system plugin, copied from SDF) -->
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <!-- wheels -->
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.4</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <!-- limits -->
      <max_linear_acceleration>0.1</max_linear_acceleration>

      <!-- input -->
      <topic>/demo/cmd_vel</topic>

      <!-- output -->
      <odom_topic>/demo/odom</odom_topic>
      <tf_topic>/tf</tf_topic>

      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>

    <!-- Joint state publisher system -->
    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
    </plugin>
  </gazebo>

</robot>
