<?xml version="1.0" ?>
<sdf version="1.11" xmlns:xacro="http://ros.org/wiki/xacro">
  <model name='sonny_panda' canonical_link='base_link'>

    <!-- ========== BEGIN SONNY CONTENT ========== -->

    <!-- Define robot constants -->
    <xacro:property name="base_width" value="0.31"/>
    <xacro:property name="base_length" value="0.42"/>
    <xacro:property name="base_height" value="0.18"/>

    <xacro:property name="wheel_radius" value="0.10"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_ygap" value="0.025"/>
    <xacro:property name="wheel_zoff" value="0.05"/>
    <xacro:property name="wheel_xoff" value="0.12"/>

    <xacro:property name="caster_xoff" value="0.14"/>

    <!-- Define some commonly used inertial properties  -->
    <xacro:macro name="box_inertia" params="m w h d">
      <inertial>
        <pose>0 0 0 ${pi/2} 0 ${pi/2}</pose>
        <mass>${m}</mass>
        <inertia>
          <ixx>${(m/12) * (h*h + d*d)}</ixx>
          <ixy>0.0</ixy>
          <ixz>0.0</ixz>
          <iyy>${(m/12) * (w*w + d*d)}</iyy>
          <iyz>0.0</iyz>
          <izz>${(m/12) * (w*w + h*h)}</izz>
        </inertia>
      </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
      <inertial>
        <pose>0 0 0 ${pi/2} 0 0</pose>
        <mass>${m}</mass>
        <inertia>
          <ixx>${(m/12) * (3*r*r + h*h)}</ixx>
          <ixy>0.0</ixy>
          <ixz>0.0</ixz>
          <iyy>${(m/12) * (3*r*r + h*h)}</iyy>
          <iyz>0.0</iyz>
          <izz>${(m/2) * (r*r)}</izz>
        </inertia>
      </inertial>
    </xacro:macro>


    <xacro:macro name="sphere_inertia" params="m r">
      <inertial>
        <mass>${m}</mass>
        <inertia>
          <ixx>${(2/5) * m * (r*r)}</ixx>
          <ixy>0.0</ixy>
          <ixz>0.0</ixz>
          <iyy>${(2/5) * m * (r*r)}</iyy>
          <iyz>0.0</iyz>
          <izz>${(2/5) * m * (r*r)}</izz>
        </inertia>
      </inertial>
    </xacro:macro>

    <!-- Robot Base -->
    <link name='base_link'>
      <must_be_base_link>true</must_be_base_link>
      <visual name="base_link_visual">
        <geometry>
          <box><size>
            ${base_length} ${base_width} ${base_height}
          </size></box>
        </geometry>
        <material>
          <ambient>0 1 1 1</ambient>
          <diffuse>0 1 1 1</diffuse>
        </material>
      </visual>

      <collision name="base_link_collision">
        <geometry>
          <box><size>
            ${base_length} ${base_width} ${base_height}
          </size></box>
        </geometry>
      </collision>
    </link>

    <!-- Robot Footprint -->
    <link name='base_footprint'>
      <pose relative_to="base_joint"/>
      <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <joint name='base_joint' type='fixed'>
      <parent>base_link</parent>
      <child>base_footprint</child>
      <pose relative_to="base_link">0.0 0.0 ${-(wheel_radius+wheel_zoff)} 0 0 0</pose>
    </joint>


    <!-- Wheels -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
      <link name="${prefix}_link">
        <pose relative_to="${prefix}_joint"/>

        <visual name="${prefix}_link_visual">
          <pose relative_to="${prefix}_link">0 0 0 ${pi/2} 0 0</pose>
          <geometry>
            <cylinder>
              <radius>${wheel_radius}</radius>
              <length>${wheel_width}</length>
            </cylinder>
          </geometry>
          <material>
            <ambient>0.3 0.3 0.3 1.0</ambient>
            <diffuse>0.7 0.7 0.7 1.0</diffuse>
          </material>
        </visual>

        <collision name="${prefix}_link_collision">
          <pose relative_to="${prefix}_link">0 0 0 ${pi/2} 0 0</pose>
          <geometry>
            <cylinder>
              <radius>${wheel_radius}</radius>
              <length>${wheel_width}</length>
            </cylinder>
          </geometry>
        </collision>

        <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
      </link>

      <joint name="${prefix}_joint" type="revolute">
        <parent>base_link</parent>
        <child>${prefix}_link</child>
        <pose relative_to="base_link">${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff} 0 0 0</pose>
        <axis>
          <xyz>0 1 0</xyz>
          <limit>
            <lower>-inf</lower>
            <upper>inf</upper>
          </limit>
        </axis>
      </joint>
    </xacro:macro>

    <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
    <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

    <link name="front_caster">
      <pose relative_to="caster_joint"/>

      <visual name="front_caster_visual">
        <geometry>
          <sphere>
            <radius>${(wheel_radius+wheel_zoff-(base_height/2))}</radius>
          </sphere>
        </geometry>
        <material>
          <ambient>0 1 1 1</ambient>
          <diffuse>0 1 1 1</diffuse>
        </material>
      </visual>

      <collision name="front_caster_collision">
        <geometry>
          <sphere>
            <radius>${(wheel_radius+wheel_zoff-(base_height/2))}</radius>
          </sphere>
        </geometry>
        <surface><friction><ode>
          <mu>0.001</mu>
          <mu2>0.001</mu2>
        </ode></friction></surface>
      </collision>

      <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
    </link>

    <joint name="caster_joint" type="fixed">
      <parent>base_link</parent>
      <child>front_caster</child>
      <pose relative_to="base_link">${caster_xoff} 0.0 ${-(base_height/2)} 0 0 0</pose>
    </joint>

    <joint name='imu_joint' type='fixed'>
      <parent>base_link</parent>
      <child>imu_link</child>
      <pose relative_to="base_link">0.0 0.0 0.01 0 0 0</pose>
    </joint>

    <link name='imu_link'>
      <pose relative_to="imu_joint"/>
      <visual name="imu_link_visual">
        <geometry>
          <box><size>
            0.1 0.1 0.1
          </size></box>
        </geometry>
      </visual>

      <collision name="imu_link_collision">
        <geometry>
          <box><size>
            0.1 0.1 0.1
          </size></box>
        </geometry>
      </collision>

      <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>

      <sensor name="imu_sensor" type="imu">
        <always_on>true</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>demo/imu</topic>
        <gz_frame_id>imu_link</gz_frame_id>
        <imu>
          <angular_velocity>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>2e-4</stddev>
                <bias_mean>0.0000075</bias_mean>
                <bias_stddev>0.0000008</bias_stddev>
              </noise>
            </z>
          </angular_velocity>
          <linear_acceleration>
            <x>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </x>
            <y>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </y>
            <z>
              <noise type="gaussian">
                <mean>0.0</mean>
                <stddev>1.7e-2</stddev>
                <bias_mean>0.1</bias_mean>
                <bias_stddev>0.001</bias_stddev>
              </noise>
            </z>
          </linear_acceleration>
        </imu>
      </sensor>
    </link>

    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <!-- wheels -->
      <left_joint>drivewhl_l_joint</left_joint>
      <right_joint>drivewhl_r_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.4</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <!-- limits -->
      <max_linear_acceleration>0.1</max_linear_acceleration>

      <!-- input -->
      <topic>/demo/cmd_vel</topic>

      <!-- output -->
      <odom_topic>/demo/odom</odom_topic>
      <tf_topic>/tf</tf_topic>

      <frame_id>odom</frame_id>
      <child_frame_id>base_link</child_frame_id>
    </plugin>

    <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
    </plugin>

    <joint name="lidar_joint" type="fixed">
      <parent>base_link</parent>
      <child>lidar_link</child>
      <pose relative_to="base_link">0.0 0.0 0.12 0 0 0</pose>
    </joint>

    <link name='lidar_link'>
      <pose relative_to="lidar_joint"/>
      <visual name="lidar_link_visual">
        <geometry>
          <cylinder>
            <radius>0.0508</radius>
            <length>0.055</length>
          </cylinder>
        </geometry>
      </visual>

      <collision name="lidar_link_collision">
        <geometry>
          <cylinder>
            <radius>0.0508</radius>
            <length>0.055</length>
          </cylinder>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.125" r="0.0508" h="0.055"/>

      <sensor name="lidar" type="gpu_lidar">
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <topic>scan</topic>
        <gz_frame_id>lidar_link</gz_frame_id>
        <lidar>
          <scan>
            <horizontal>
              <samples>360</samples>
              <resolution>1.000000</resolution>
              <min_angle>0.000000</min_angle>
              <max_angle>6.280000</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.120000</min>
            <max>3.5</max>
            <resolution>0.015000</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </lidar>
      </sensor>
    </link>



    <!-- =========== END SONNY CONTENT =========== -->



    <!-- ==================================================================================================================================== -->
    <!-- ==================================================================================================================================== -->


    <!-- ========== BEGIN PANDA CONTENT ========== -->
    <link name='panda_link0'>
      <inertial>
        <pose>-0.041017999999999999 -0.00013999999999999999 0.049973999999999998 0 0 0</pose>
        <mass>0.62976900000000002</mass>
        <inertia>
          <ixx>0.00315</ixx>
          <ixy>8.2903999999999996e-07</ixy>
          <ixz>0.00014999999999999999</ixz>
          <iyy>0.0038800000000000002</iyy>
          <iyz>8.2299000000000006e-06</iyz>
          <izz>0.0042849999999999997</izz>
        </inertia>
      </inertial>
      <collision name='panda_link0_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link0.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link0_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link0.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint1' type='revolute'>
      <pose relative_to='panda_link0'>0 0 0.33300000000000002 0 0 0</pose>
      <parent>panda_link0</parent>
      <child>panda_link1</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-2.9670999999999998</lower>
          <upper>2.9670999999999998</upper>
          <effort>87</effort>
          <velocity>2.3925000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link1'>
      <pose relative_to='panda_joint1'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0.003875 0.002081 -0.047620000000000003 0 0 0</pose>
        <mass>4.9706840000000003</mass>
        <inertia>
          <ixx>0.70337000000000005</ixx>
          <ixy>-0.00013899999999999999</ixy>
          <ixz>0.0067720000000000002</ixz>
          <iyy>0.70660999999999996</iyy>
          <iyz>0.019168999999999999</iyz>
          <izz>0.0091170000000000001</izz>
        </inertia>
      </inertial>
      <collision name='panda_link1_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link1.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link1_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link1.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint2' type='revolute'>
      <pose relative_to='panda_link1'>0 0 0 -1.57079632679 0 0</pose>
      <parent>panda_link1</parent>
      <child>panda_link2</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1.8326</lower>
          <upper>1.8326</upper>
          <effort>87</effort>
          <velocity>2.3925000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link2'>
      <pose relative_to='panda_joint2'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>-0.0031410000000000001 -0.028719999999999999 0.0034949999999999998 0 0 0</pose>
        <mass>0.646926</mass>
        <inertia>
          <ixx>0.0079620000000000003</ixx>
          <ixy>-0.0039249999999999997</ixy>
          <ixz>0.010253999999999999</ixz>
          <iyy>0.02811</iyy>
          <iyz>0.00070399999999999998</iyz>
          <izz>0.025995000000000001</izz>
        </inertia>
      </inertial>
      <collision name='panda_link2_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link2.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link2_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link2.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint3' type='revolute'>
      <pose relative_to='panda_link2'>0 -0.316 0 1.57079632679 0 0</pose>
      <parent>panda_link2</parent>
      <child>panda_link3</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-2.9670999999999998</lower>
          <upper>2.9670999999999998</upper>
          <effort>87</effort>
          <velocity>2.3925000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link3'>
      <pose relative_to='panda_joint3'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0.027518000000000001 0.039252000000000002 -0.066502000000000006 0 0 0</pose>
        <mass>3.2286039999999998</mass>
        <inertia>
          <ixx>0.037241999999999997</ixx>
          <ixy>-0.0047609999999999996</ixy>
          <ixz>-0.011396</ixz>
          <iyy>0.036155</iyy>
          <iyz>-0.012805</iyz>
          <izz>0.010829999999999999</izz>
        </inertia>
      </inertial>
      <collision name='panda_link3_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link3.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link3_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link3.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint4' type='revolute'>
      <pose relative_to='panda_link3'>0.082500000000000004 0 0 1.57079632679 0 0</pose>
      <parent>panda_link3</parent>
      <child>panda_link4</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-3.1415999999999999</lower>
          <upper>0.087300000000000003</upper>
          <effort>87</effort>
          <velocity>2.3925000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link4'>
      <pose relative_to='panda_joint4'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>-0.053170000000000002 0.104419 0.027453999999999999 0 0 0</pose>
        <mass>3.5878950000000001</mass>
        <inertia>
          <ixx>0.025853000000000001</ixx>
          <ixy>0.007796</ixy>
          <ixz>-0.0013320000000000001</ixz>
          <iyy>0.019552</iyy>
          <iyz>0.0086409999999999994</iyz>
          <izz>0.028323000000000001</izz>
        </inertia>
      </inertial>
      <collision name='panda_link4_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link4.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link4_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link4.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint5' type='revolute'>
      <pose relative_to='panda_link4'>-0.082500000000000004 0.38400000000000001 0 -1.57079632679 0 0</pose>
      <parent>panda_link4</parent>
      <child>panda_link5</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-2.9670999999999998</lower>
          <upper>2.9670999999999998</upper>
          <effort>12</effort>
          <velocity>2.871</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link5'>
      <pose relative_to='panda_joint5'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>-0.011953 0.041064999999999997 -0.038436999999999999 0 0 0</pose>
        <mass>1.225946</mass>
        <inertia>
          <ixx>0.035548999999999997</ixx>
          <ixy>-0.002117</ixy>
          <ixz>-0.0040369999999999998</ixz>
          <iyy>0.029474</iyy>
          <iyz>0.00022900000000000001</iyz>
          <izz>0.0086269999999999993</izz>
        </inertia>
      </inertial>
      <collision name='panda_link5_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link5.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link5_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link5.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint6' type='revolute'>
      <pose relative_to='panda_link5'>0 0 0 1.57079632679 0 0</pose>
      <parent>panda_link5</parent>
      <child>panda_link6</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-0.087300000000000003</lower>
          <upper>3.8222999999999998</upper>
          <effort>12</effort>
          <velocity>2.871</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link6'>
      <pose relative_to='panda_joint6'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0.060149000000000001 -0.014116999999999999 -0.010517 0 0 0</pose>
        <mass>1.666555</mass>
        <inertia>
          <ixx>0.001964</ixx>
          <ixy>0.00010900000000000001</ixy>
          <ixz>-0.001158</ixz>
          <iyy>0.0043540000000000002</iyy>
          <iyz>0.00034099999999999999</iyz>
          <izz>0.0054330000000000003</izz>
        </inertia>
      </inertial>
      <collision name='panda_link6_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link6.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link6_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link6.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_joint7' type='revolute'>
      <pose relative_to='panda_link6'>0.087999999999999995 0 0 1.57079632679 0 0</pose>
      <parent>panda_link6</parent>
      <child>panda_link7</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-2.9670999999999998</lower>
          <upper>2.9670999999999998</upper>
          <effort>12</effort>
          <velocity>2.871</velocity>
        </limit>
        <dynamics>
          <damping>0.0030000000000000001</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_link7'>
      <pose relative_to='panda_joint7'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0.0017561014923937609 0.001388201581866041 0.099156442983455717 0 0 0</pose>
        <mass>1.465522</mass>
        <inertia>
          <ixx>0.016396041602866059</ixx>
          <ixy>0.00039496396473183529</ixy>
          <ixz>-0.00070411561565401231</ixz>
          <iyy>0.013973402524881631</iyy>
          <iyz>-0.001053808768508498</iyz>
          <izz>0.0066753082423586883</izz>
        </inertia>
      </inertial>
      <collision name='panda_link7_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/link7.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <collision name='panda_link7_fixed_joint_lump__panda_hand_collision_1'>
        <pose>0 0 0.107 0 0 -0.78539816339699997</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/hand.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_link7_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/link7.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <visual name='panda_link7_fixed_joint_lump__panda_hand_visual_1'>
        <pose>0 0 0.107 0 0 -0.78539816339699997</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/hand.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_finger_joint1' type='prismatic'>
      <pose relative_to='panda_link7'>0 0 0.16539999999999999 0 0 -0.78539816339699997</pose>
      <parent>panda_link7</parent>
      <child>panda_leftfinger</child>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>0</lower>
          <upper>0.040000000000000001</upper>
          <effort>20</effort>
          <velocity>0.20000000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.29999999999999999</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_leftfinger'>
      <pose relative_to='panda_finger_joint1'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>0.014999999999999999</mass>
        <inertia>
          <ixx>2.3750000000000001e-06</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>2.3750000000000001e-06</iyy>
          <iyz>0</iyz>
          <izz>7.5000000000000002e-07</izz>
        </inertia>
      </inertial>
      <collision name='panda_leftfinger_collision'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/finger.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_leftfinger_visual'>
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/finger.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <joint name='panda_finger_joint2' type='prismatic'>
      <pose relative_to='panda_link7'>0 0 0.16539999999999999 0 0 -0.78539816339699997</pose>
      <parent>panda_link7</parent>
      <child>panda_rightfinger</child>
      <axis>
        <xyz>0 -1 0</xyz>
        <mimic joint='panda_finger_joint1'>
          <multiplier>1</multiplier>
          <offset>0</offset>
          <reference>0</reference>
        </mimic>
        <limit>
          <lower>0</lower>
          <upper>0.040000000000000001</upper>
          <effort>20</effort>
          <velocity>0.20000000000000001</velocity>
        </limit>
        <dynamics>
          <damping>0.29999999999999999</damping>
          <friction>0</friction>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
        </dynamics>
      </axis>
    </joint>
    <link name='panda_rightfinger'>
      <pose relative_to='panda_finger_joint2'>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>0.14999999999999999</mass>
        <inertia>
          <ixx>2.3750000000000001e-06</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>2.3750000000000001e-06</iyy>
          <iyz>0</iyz>
          <izz>7.5000000000000002e-07</izz>
        </inertia>
      </inertial>
      <collision name='panda_rightfinger_collision'>
        <pose>0 0 0 0 0 -3.1415926535895871</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/collision/finger.stl</uri>
          </mesh>
        </geometry>
      </collision>
      <visual name='panda_rightfinger_visual'>
        <pose>0 0 0 0 0 -3.1415926535895871</pose>
        <geometry>
          <mesh>
            <scale>1 1 1</scale>
            <uri>file:///home/reuben/moveit_ws/install/moveit_resources_panda_description/share/moveit_resources_panda_description/meshes/visual/finger.dae</uri>
          </mesh>
        </geometry>
      </visual>
    </link>
    <plugin name='gz_ros2_control::GazeboSimROS2ControlPlugin' filename='gz_ros2_control-system'>
      <parameters>/home/reuben/moveit_ws/src/panda_moveit_config/config/ros2_controllers.yaml</parameters>
    </plugin>
    <frame name='panda_hand_joint' attached_to='panda_link8'>
      <pose>0 0 0 0 0 -0.78539816339699997</pose>
    </frame>
    <frame name='panda_hand' attached_to='panda_hand_joint'>
      <pose>0 0 0 0 0 0</pose>
    </frame>
    <frame name='panda_joint8' attached_to='panda_link7'>
      <pose>0 0 0.107 0 0 0</pose>
    </frame>
    <frame name='panda_link8' attached_to='panda_joint8'>
      <pose>0 0 0 0 0 0</pose>
    </frame>


    <!-- =========== END PANDA CONTENT =========== -->


    <!-- ==================================================================================================================================== -->
    <!-- ==================================================================================================================================== -->

    <joint name='panda_on_sonny' type='fixed'>
      <parent>base_link</parent>
      <child>panda_link0</child>
      <pose relative_to="base_link">0.0 0.0 ${base_height/2} 0 0 0</pose>
    </joint>

  </model>
</sdf>

